# Generated by Django 5.0.3 on 2024-03-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('cooking_time', models.IntegerField()),
                ('tags', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='recipes/img')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
        ),
    ]
