# Generated by Django 5.0.3 on 2024-05-10 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_recipe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="cooking_time",
        ),
    ]
