# Generated by Django 5.0.3 on 2024-05-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_alter_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="pub_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
