# Generated by Django 5.0.3 on 2024-05-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_recipe_is_published_recipe_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
