# Generated by Django 5.0.3 on 2024-05-17 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_recipe_pub_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"permissions": [("publish_recipe", "Can publish a Recipe")]},
        ),
    ]
