# Generated by Django 5.0.3 on 2024-05-21 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_alter_recipe_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "permissions": [
                    ("publish_recipe", "Can publish a Recipe"),
                    ("edit_custom_recipe", "Can edit a Recipe"),
                    ("remove_recipe", "Can delete a Recipe"),
                    ("approve_recipe", "Can approve a Recipe"),
                ]
            },
        ),
    ]
