# Generated by Django 5.0.3 on 2024-05-23 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"permissions": [("approve_recipe", "Can approve a Recipe")]},
        ),
    ]
