# Generated by Django 5.0.3 on 2024-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_alter_recipe_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="topic",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Culture", "Culture"),
                    ("Personal", "Personal"),
                ],
                default="Food",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
