# Generated by Django 5.0.3 on 2024-05-25 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0014_recipe_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="topic",
            new_name="category",
        ),
    ]
