# Generated by Django 5.0.3 on 2024-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0015_rename_topic_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Culture", "Culture"),
                    ("Africa", "Africa"),
                ],
                max_length=10,
            ),
        ),
    ]
